### ISSUE TITLE
Slidem Maintenance

### ISSUE THREAD

**Issue by bennypowers** [ruphin/slidem#26]
Hello!

I'm interested in taking on the maintenance of slidem. I have a number of features [patched in to the library](https://github.com/apollo-elements/apollo-elements/blob/main/patches/slidem%2B1.2.8.patch) which I'd like to upstream.

- Presenter notes (`<p slot="presenter">`)
- Slides progress bar
- Custom keybindings
- Update document title
- More CSS Shadow parts
- Slide Watermarks (via slots)
- `past` and `current` step attributes
- Removing ie11 support
- `activated` event on slides

Beyond that I have a number of ideas to update and modernize the codebase, and for future features like split screen presenter mode across hosts (maybe via simple http auth)

@ruphin would you be interested and willing to give me contributor access to the repo?

**Comment by ruphin** [comment]
Yes, I can definitely do that! I tried to modernise the codebase a while ago but ended up not having enough time to finish.

I agree with all the proposed changes, and I'm excited to see what you'll do with it.

**Comment by ruphin** [comment]
Done 👍
